name: Node.js CI

on: 
  push:
    paths: 
      - 'FrontEnd/**'
  pull_request:
    paths: 
      - 'FrontEnd/**'
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./FrontEnd/fairman-personal-site
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install and build
      working-directory: ${{env.working-directory}}
      run: |
        npm ci
        npm run build:ci
      env:
        CI: true
