name: Node.js CI

on: 
  push:
    paths: 
      - FrontEnd/**
  pull_request:
    paths: 
      - FrontEnd/**
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./FrontEnd/fairman-personal-site
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install NPM Packages
      working-directory: ${{env.working-directory}}
      run: npm install
    - name: Install Angular
      working-directory: ${{env.working-directory}}
      run: npm install @angular/cli
    - name: Build the site
      working-directory: ${{env.working-directory}}
      run: ng build fairman-personal-site
    - name: Run the tests
      working-directory: ${{env.working-directory}}
      run: ng test fairman-personal-site
      env:
        CI: true
